# Generated by Django 2.0.7 on 2018-07-22 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('i_customer', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('street_addr', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mail_from', models.CharField(max_length=200)),
                ('payment_currency', models.CharField(max_length=200)),
                ('payment_method', models.PositiveSmallIntegerField()),
                ('i_tariff', models.PositiveSmallIntegerField()),
                ('api_access', models.PositiveSmallIntegerField()),
                ('api_mgmt', models.PositiveSmallIntegerField()),
                ('i_commission_agent', models.PositiveSmallIntegerField()),
                ('tariffs_mgmt', models.PositiveSmallIntegerField()),
                ('vouchers_mgmt', models.PositiveSmallIntegerField()),
                ('accounts_mgmt', models.PositiveSmallIntegerField()),
                ('customers_mgmt', models.PositiveSmallIntegerField()),
                ('system_mgmt', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('i_lang', models.CharField(max_length=200)),
                ('i_export_type', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='did',
            fields=[
                ('i_did', models.AutoField(primary_key=True, serialize=False)),
                ('did', models.CharField(max_length=200)),
                ('incoming_did', models.CharField(max_length=200)),
                ('i_ivr_application', models.PositiveSmallIntegerField()),
                ('i_account', models.PositiveSmallIntegerField()),
                ('i_vendor', models.PositiveSmallIntegerField()),
                ('i_connection', models.PositiveSmallIntegerField()),
                ('i_did_delegation', models.PositiveSmallIntegerField()),
                ('delegated_to', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
