# Generated by Django 2.0.7 on 2018-07-22 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('i_account', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('street_addr', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('payment_currency', models.CharField(max_length=200)),
                ('blocked', models.PositiveSmallIntegerField()),
                ('payment_method', models.PositiveSmallIntegerField()),
                ('i_commission_agent', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('i_lang', models.CharField(max_length=200)),
                ('i_export_type', models.PositiveSmallIntegerField()),
                ('on_payment_action', models.PositiveSmallIntegerField()),
                ('preferred_codec', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
