# Generated by Django 2.0.7 on 2018-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='debit_credit_cards_enabled',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='did_pool_enabled',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='ivr_apps_enabled',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='max_calls_per_second',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='min_payment_amount',
            field=models.FloatField(default=None),
        ),
    ]
