# Generated by Django 2.0.7 on 2018-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0005_auto_20180722_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='debit_credit_cards_enabled',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='did_pool_enabled',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ivr_apps_enabled',
        ),
        migrations.AlterField(
            model_name='customer',
            name='accounts_mgmt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='api_access',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='api_mgmt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customers_mgmt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='i_commission_agent',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='i_export_type',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='i_tariff',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='max_calls_per_second',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='min_payment_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_method',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='system_mgmt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tariffs_mgmt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vouchers_mgmt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
