# Generated by Django 2.0.7 on 2018-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0008_auto_20180722_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
