# Generated by Django 2.0.7 on 2018-07-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0011_auto_20180722_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='credit_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='web_login',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='i_account',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='i_customer',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='did',
            name='i_did',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='i_vendor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
