# Generated by Django 2.0.7 on 2018-07-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0012_auto_20180722_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='delegated_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='did',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='i_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='i_connection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='i_did_delegation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='i_ivr_application',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='i_vendor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='incoming_did',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
