# Generated by Django 2.0.7 on 2018-07-23 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0013_auto_20180722_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='histCustomer',
            fields=[
                ('i_customer', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('street_addr', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mail_from', models.CharField(max_length=200)),
                ('payment_currency', models.CharField(max_length=200)),
                ('payment_method', models.IntegerField(blank=True, null=True)),
                ('i_tariff', models.IntegerField(blank=True, null=True)),
                ('credit_limit', models.FloatField(blank=True, null=True)),
                ('min_payment_amount', models.FloatField(blank=True, null=True)),
                ('api_access', models.IntegerField(blank=True, null=True)),
                ('api_mgmt', models.IntegerField(blank=True, null=True)),
                ('i_commission_agent', models.IntegerField(blank=True, null=True)),
                ('tariffs_mgmt', models.IntegerField(blank=True, null=True)),
                ('vouchers_mgmt', models.IntegerField(blank=True, null=True)),
                ('accounts_mgmt', models.IntegerField(blank=True, null=True)),
                ('customers_mgmt', models.IntegerField(blank=True, null=True)),
                ('system_mgmt', models.IntegerField(blank=True, null=True)),
                ('did_pool_enabled', models.NullBooleanField()),
                ('ivr_apps_enabled', models.NullBooleanField()),
                ('debit_credit_cards_enabled', models.NullBooleanField()),
                ('description', models.TextField()),
                ('i_lang', models.CharField(max_length=200)),
                ('i_export_type', models.IntegerField(blank=True, null=True)),
                ('max_calls_per_second', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
