# Generated by Django 2.0.7 on 2018-07-25 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0014_histcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='histDid',
            fields=[
                ('i_did', models.IntegerField(primary_key=True, serialize=False)),
                ('did', models.CharField(blank=True, max_length=200, null=True)),
                ('incoming_did', models.CharField(blank=True, max_length=200, null=True)),
                ('i_ivr_application', models.IntegerField(blank=True, null=True)),
                ('i_account', models.IntegerField(blank=True, null=True)),
                ('i_vendor', models.IntegerField(blank=True, null=True)),
                ('i_connection', models.IntegerField(blank=True, null=True)),
                ('i_did_delegation', models.IntegerField(blank=True, null=True)),
                ('delegated_to', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='histCustomer',
        ),
    ]
