# Generated by Django 2.0.7 on 2018-07-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sippy', '0015_auto_20180725_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histdid',
            name='description',
        ),
        migrations.RemoveField(
            model_name='histdid',
            name='i_account',
        ),
        migrations.RemoveField(
            model_name='histdid',
            name='i_connection',
        ),
        migrations.RemoveField(
            model_name='histdid',
            name='i_did_delegation',
        ),
        migrations.RemoveField(
            model_name='histdid',
            name='i_ivr_application',
        ),
        migrations.RemoveField(
            model_name='histdid',
            name='i_vendor',
        ),
        migrations.RemoveField(
            model_name='histdid',
            name='incoming_did',
        ),
        migrations.RemoveField(
            model_name='histdid',
            name='published_date',
        ),
    ]
